name: SimpleTpaPlugin
version: '${version}'
main: org.owcadev.tpaplugin.TpaPlugin
api-version: '1.20'
commands:
  tpa:
    description: tpa
    usage: /tpa <Player>
  tpaccept:
    description: tpaccept
    usage: /tpaccept <Player>
  tpadeny:
    description: tpadeny
    usage: /tpadeny <Player>
  tpasetime:
    description: tpasetime
    usage: /tpasetime <Time>